name: Visualize SRA Data

on:
    schedule:
        - cron: '0 0 * * *' # Runs at 00:00 UTC every day
    workflow_dispatch:

jobs:
    visualize-and-commit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                  pip install pandas matplotlib

            - name: Fetch and Plot SRA Data
              run: |
                  python fetch_and_plot.py sra_data_growth.png

            - name: Update Date in README.md
              run: |
                  DATE=$(date +'%Y-%m-%d')
                  sed -i "s/^\\*\\*updated on:.*/**updated on: ${DATE}**/" README.md

            - name: Commit and Push Changes
              env:
                  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
              run: |
                  git config --global user.name 'GitHub Actions'
                  git config --global user.email 'actions@github.com'
                  git add sra_data_growth.png README.md
                  git commit -m "$(date +'%Y-%m-%d')" || echo "No changes to commit"
                  git push --set-upstream https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main